---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Add Percona toolkit repo
  yum:
    name: 'http://www.percona.com/downloads/percona-release/redhat/0.1-6/percona-release-0.1-6.noarch.rpm'
    state: latest

- name: Install packages wanted
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - zsh
      - tmux
      - emacs
      - sysstat
      - dstat
      - htop
      - nginx
      - percona-toolkit
