---
- name: Install epel-release
  yum:
    name: epel-release
    state: latest

- name: Install Software Collections
  yum:
    name: centos-release-scl
    state: latest

- name: Add repo for MySQL 8.0 GA
  yum:
    name: 'https://dev.mysql.com/get/mysql80-community-release-el7-1.noarch.rpm'
    state: latest

- name: Install packages wanted
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - zip
      - unzip
      - zsh
      - tmux
      - emacs
      - git
      - sysstat
      - dstat
      - htop
      - nginx
      - rh-ruby25
      - mysql-community-server
      - mysql-community-client
      - mysql-community-libs
      - mysql-community-libs-compat

- name: Install Percona Toolkit
  yum:
    name: 'https://www.percona.com/downloads/percona-toolkit/3.0.12/binary/redhat/7/x86_64/percona-toolkit-3.0.12-1.el7.x86_64.rpm'
    state: latest

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest

- name: systemctl enable nginx
  systemd:
    name: nginx
    enabled: yes

- name: systemctl enable mysqld
  systemd:
    name: mysqld
    enabled: yes

- name: Download alp
  get_url:
    url: 'https://github.com/tkuchiki/alp/releases/download/v0.3.1/alp_linux_amd64.zip'
    dest: /tmp/alp_linux_amd64.zip
    owner: root
    group: root
    mode: 0644

- name: Unzip alp
  unarchive:
    remote_src: yes
    src: /tmp/alp_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755

- name: Download mysqldef
  get_url:
    url: 'https://github.com/k0kubun/sqldef/releases/download/v0.4.1/mysqldef_linux_amd64.tar.gz'
    dest: /tmp/mysqldef_linux_amd64.tar.gz
    owner: root
    group: root
    mode: 0644

- name: Unzip mysqldef
  unarchive:
    remote_src: yes
    src: /tmp/mysqldef_linux_amd64.tar.gz
    dest: /usr/local/bin
    mode: 0755

- name: Copy files under /etc
  copy:
    src: etc/
    dest: /etc/
    owner: root
    group: root
    mode: 0644

- name: Copy files under /root
  copy:
    src: root/
    dest: /root/
    owner: root
    group: root
    mode: 0644
