- name: Install packages wanted
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - zip
      - unzip
      - vim
      - tmux
      - git
      - sysstat
      - dstat
      - htop
      - byobu
      - zlib1g-dev 
      - uuid-dev 
      - libuv1-dev 
      - liblz4-dev 
      - libjudy-dev
      - libssl-dev 
      - libmnl-dev 
      - python3-pymysql
      - gcc 
      - make  
      - autoconf 
      - autoconf-archive 
      - autogen 
      - automake 
      - pkg-config 
      - curl 
      - python
      - percona-toolkit


- name: Upgrade all packages
  apt:
    name: '*'
    force_apt_get: True
    state: latest

- name: git clone
  git:
    repo: https://github.com/netdata/netdata.git
    ##/home/isucon/netdataに変更の可能性あり
    dest: /root/netdata
    depth: 1
    
- name: install netdata
  shell: ./netdata-installer.sh --dont-wait
  args:
    ##/home/isucon/netdataに変更の可能性あり
    chdir: /root/netdata

- name: Download alp
  get_url:
    url: 'https://github.com/tkuchiki/alp/releases/download/v1.0.3/alp_linux_amd64.zip'
    dest: /tmp/alp_linux_amd64.zip
    owner: root
    group: root
    mode: 0644

- name: Unzip alp
  unarchive:
    remote_src: yes
    src: /tmp/alp_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755

- name: Download slackcat
  get_url:
    url: 'https://github.com/vektorlab/slackcat/releases/download/v1.6/slackcat-1.6-linux-amd64'
    dest: /tmp/slackcat
    owner: root
    group: root
    mode: 0644

- name: stat slackcat
  stat: path=/tmp/slackcat
  register: slackcat_stat

- name: mv slackcat
  command: mv /tmp/slackcat /usr/local/bin/slackcat
  when: slackcat_stat.stat.exists

- name: chmod slackcat
  file:
    path: /usr/local/bin/slackcat
    owner: root
    group: root
    mode: 0755

- name: Copy files shell
  copy:
    src: shell/
    dest: /root/
    owner: root
    group: root
    mode: 0755