- name: Install packages wanted
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - zip
      - unzip
      - vim
      - tmux
      - git
      - sysstat
      - dstat
      - htop
      - byobu
      - zlib1g-dev 
      - uuid-dev 
      - libuv1-dev 
      - liblz4-dev 
      - libjudy-dev
      - libssl-dev 
      - libmnl-dev 
      - gcc 
      - make  
      - autoconf 
      - autoconf-archive 
      - autogen 
      - automake 
      - pkg-config 
      - curl 
      - python
      - percona-toolkit


- name: Upgrade all packages
  apt:
    name: '*'
    force_apt_get: True
    state: latest

- name: git clone
  git:
    repo: https://github.com/netdata/netdata.git
    ##/home/isucon/netdataに変更の可能性あり
    dest: /root/netdata
    depth: 1
    
- name: install netdata
  shell: ./netdata-installer.sh --dont-wait
  args:
    ##/home/isucon/netdataに変更の可能性あり
    chdir: /root/netdata

# - name: systemctl enable nginx
#   systemd:
#     name: nginx
#     enabled: yes


##やるか微妙??
# - name: disable apparmor
#   systemd:
#     name: apparmor.service
#     enabled: no
#     state: stopped


- name: Download alp
  get_url:
    url: 'https://github.com/tkuchiki/alp/releases/download/v0.4.0/alp_linux_amd64.zip'
    dest: /tmp/alp_linux_amd64.zip
    owner: root
    group: root
    mode: 0644

- name: Unzip alp
  unarchive:
    remote_src: yes
    src: /tmp/alp_linux_amd64.zip
    dest: /usr/local/bin
    mode: 0755

# # - name: Download mysqldef
# #   get_url:
# #     url: 'https://github.com/k0kubun/sqldef/releases/download/v0.4.1/mysqldef_linux_amd64.tar.gz'
# #     dest: /tmp/mysqldef_linux_amd64.tar.gz
# #     owner: root
# #     group: root
# #     mode: 0644

# # - name: Unzip mysqldef
# #   unarchive:
# #     remote_src: yes
# #     src: /tmp/mysqldef_linux_amd64.tar.gz
# #     dest: /usr/local/bin
# #     mode: 0755

- name: Copy files under /etc
  copy:
    src: etc/mysql/my.cnf
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644

- name: Copy files under /root
  copy:
    src: root/
    dest: /root/
    owner: root
    group: root
    mode: 0644

- name: chmod 700
  file:
    path: /root/.ssh
    owner: root
    group: root
    mode: 0700

- name: chmod 600
  file:
    path: /root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

# - name: systemctl enable mysql
#   systemd:
#     name: mysql
#     enabled: yes
